[common]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_flags = -D TENSTAR_ESP32C3
lib_deps = 
    zinggjm/GxEPD2@^1.6.0
    adafruit/Adafruit GFX Library@^1.11.11
    marvinroger/AsyncMqttClient@^0.9.0
    adafruit/Adafruit BME280 Library@^2.2.4
    robtillaart/INA226@^0.6.0
    bblanchon/ArduinoJson@^7.3.0
    adafruit/Adafruit NeoPixel@^1.12.4

[env:krvkweather_frame]
extends = common
upload_port = COM9

[env:krvkweather_frame_ota]
extends = common
upload_protocol = espota
upload_port = 192.168.0.207